### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by griffinlacek** [justingould76/prj-rev-bwfs-dasmoto#7]
**Grade:** Meets Expectations

**Summary:** This project has a lot of good work and closely meets the spec! A few areas of improvement are remembering consistent HTML indentation (indent children from parent elements even body) and trying to reduce repeated CSS styles, all of which will make your code more readable and maintainable. 

As a further challenge, think about and try to change the page to have the item divs horizontally aligned instead of vertical aligned. There’s a few different ways to do this, but one way involves set widths and inline-block styling! This is a good resource for learning more: http://learnlayout.com/inline- block.html.

I’d also suggest checking out HTML codes, which will help explain my comment on the & usage in your HTML!

Good work!

**Comment by justingould76** [comment]
Read about &amp;...Thank you for sharing that.
